# Generated by Django 4.1 on 2022-09-04 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_empresa', models.IntegerField()),
                ('Nit', models.IntegerField()),
                ('NombreEmpresa', models.CharField(max_length=30)),
                ('Direccion', models.CharField(max_length=50)),
                ('Telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Documento', models.IntegerField()),
                ('rol', models.IntegerField()),
                ('correo', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=10)),
                ('NombreEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appreto1.empresa')),
            ],
        ),
    ]
