# Generated by Django 4.1 on 2022-09-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreto1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('Id_Rol', models.IntegerField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=30)),
                ('Documento', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='rol',
            new_name='Id_rol',
        ),
    ]
