# Generated by Django 4.1 on 2022-09-12 02:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrasena',
            fields=[
                ('IdContrasena', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('Contrasena', models.CharField(max_length=100)),
                ('FechaCreacion', models.DateTimeField(default=datetime.datetime.now)),
                ('FechaModificacion', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('IdEmpleado', models.IntegerField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Imagen', models.ImageField(upload_to='')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Telefono', models.CharField(max_length=20)),
                ('Cargo', models.CharField(max_length=100)),
                ('FechaCreacion', models.DateTimeField(default=datetime.datetime.now)),
                ('FechaModificacion', models.DateTimeField(default=datetime.datetime.now)),
                ('IdContrasena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appciclo.contrasena')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('IdEmpresa', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Nit', models.CharField(max_length=10)),
                ('Ciudad', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=20)),
                ('SectorProductivo', models.CharField(max_length=50)),
                ('FechaCreacion', models.DateTimeField(default=datetime.datetime.now)),
                ('FechaModificacion', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('IdRol', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('FechaCreacion', models.DateTimeField(default=datetime.datetime.now)),
                ('FechaModificacion', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('IdIngreso', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('Concepto', models.CharField(max_length=300)),
                ('Monto', models.CharField(max_length=100)),
                ('FechaCreacion', models.DateTimeField(default=datetime.datetime.now)),
                ('FechaModificacion', models.DateTimeField(default=datetime.datetime.now)),
                ('IdEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appciclo.empleado')),
                ('IdEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appciclo.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='IdEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appciclo.empresa'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='IdRol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appciclo.role'),
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('IdEgreso', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('Concepto', models.CharField(max_length=300)),
                ('Monto', models.CharField(max_length=100)),
                ('FechaCreacion', models.DateTimeField(default=datetime.datetime.now)),
                ('FechaModificacion', models.DateTimeField(default=datetime.datetime.now)),
                ('IdEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appciclo.empleado')),
                ('IdEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appciclo.empresa')),
            ],
        ),
    ]
