# Generated by Django 4.1 on 2022-09-12 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appciclo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Rol',
        ),
    ]
