# Generated by Django 4.1 on 2022-09-25 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appciclo', '0003_alter_empresa_nit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='Imagen',
        ),
    ]
