# Generated by Django 4.1 on 2022-09-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appciclo', '0005_alter_empleado_idcontrasena_delete_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='IdRol',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
